[build]
  command = "npm install --prefix netlify/functions && echo 'Building...'"
  publish = "/"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 
